import { PrismaClient, PropertyTenure, PropertyType, PropertyStatus } from "@prisma/client";

const prisma = new PrismaClient({
  datasources: { db: { url: process.env.DIRECT_URL || process.env.DATABASE_URL } },
});

interface PropertySeed {
  plotNumber: string;
  title: string;
  description: string;
  district: string;
  county?: string;
  subcounty?: string;
  village?: string;
  size: number;
  tenure: PropertyTenure;
  type: PropertyType;
  price: number;
  latitude?: number;
  longitude?: number;
}

const PROPERTIES: PropertySeed[] = [
  // Kampala - Central Region (8 properties)
  {
    plotNumber: "KMP-001-RES",
    title: "Spacious Residential Lot in Kololo",
    description: "Premium residential plot with excellent road access near Kololo Hill. Ideal for luxury home development.",
    district: "Kampala",
    county: "Kampala Central",
    subcounty: "Kololo",
    village: "Kololo",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 450000000,
    latitude: 0.3092,
    longitude: 32.5825,
  },
  {
    plotNumber: "KMP-002-COM",
    title: "Commercial Property on Kampala Road",
    description: "Strategic commercial land on main Kampala Road corridor. Perfect for retail or office development.",
    district: "Kampala",
    county: "Kampala Central",
    subcounty: "Nakasero",
    village: "Nakasero",
    size: 0.25,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 550000000,
    latitude: 0.3156,
    longitude: 32.5818,
  },
  {
    plotNumber: "KMP-003-MIX",
    title: "Mixed-Use Development Site in Makindye",
    description: "Large mixed-use land suitable for residential and commercial development. Near Muyenga Road.",
    district: "Kampala",
    county: "Makindye",
    subcounty: "Makindye",
    village: "Makindye",
    size: 1.2,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.MIXED_USE,
    price: 750000000,
    latitude: 0.2833,
    longitude: 32.5939,
  },
  {
    plotNumber: "KMP-004-RES",
    title: "Residential Plot in Ntinda",
    description: "Residential property in fast-developing Ntinda area. Good investment potential.",
    district: "Kampala",
    county: "Nakawa",
    subcounty: "Ntinda",
    village: "Ntinda",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 320000000,
    latitude: 0.3708,
    longitude: 32.6017,
  },
  {
    plotNumber: "KMP-005-AGR",
    title: "Agricultural Land near Kampala",
    description: "Fertile agricultural land suitable for farming or agribusiness venture.",
    district: "Kampala",
    county: "Kawempe",
    subcounty: "Kawempe",
    village: "Bwaise",
    size: 2.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 180000000,
    latitude: 0.3533,
    longitude: 32.5511,
  },
  {
    plotNumber: "KMP-006-IND",
    title: "Industrial Plot near Jinja Road",
    description: "Well-positioned industrial land near Jinja Road corridor with good transport access.",
    district: "Kampala",
    county: "Nakawa",
    subcounty: "Naguru",
    village: "Naguru",
    size: 0.8,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.INDUSTRIAL,
    price: 380000000,
    latitude: 0.3456,
    longitude: 32.5967,
  },
  {
    plotNumber: "KMP-007-RES",
    title: "Modern Residential Home in Mbuya",
    description: "Suburban residential area with developed infrastructure and community facilities.",
    district: "Kampala",
    county: "Nakawa",
    subcounty: "Mbuya",
    village: "Mbuya",
    size: 0.35,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 280000000,
    latitude: 0.3289,
    longitude: 32.6156,
  },
  {
    plotNumber: "KMP-008-COM",
    title: "Commercial Space in Rubaga",
    description: "Commercial property in bustling Rubaga area with high foot traffic.",
    district: "Kampala",
    county: "Rubaga",
    subcounty: "Rubaga",
    village: "Rubaga",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 420000000,
    latitude: 0.2966,
    longitude: 32.5361,
  },

  // Wakiso - Central Region (7 properties)
  {
    plotNumber: "WAK-001-RES",
    title: "Residential Land in Entebbe",
    description: "Prime residential location near Entebbe with proximity to the airport.",
    district: "Wakiso",
    county: "Entebbe Municipality",
    subcounty: "Entebbe",
    village: "Entebbe",
    size: 0.6,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 350000000,
    latitude: 0.0412,
    longitude: 32.4516,
  },
  {
    plotNumber: "WAK-002-RES",
    title: "Suburban Home in Kira",
    description: "Developing suburban area with good road network and nearby schools.",
    district: "Wakiso",
    county: "Kyadondo East",
    subcounty: "Kira",
    village: "Kira",
    size: 0.45,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 220000000,
    latitude: 0.2317,
    longitude: 32.5367,
  },
  {
    plotNumber: "WAK-003-RES",
    title: "Residential Plot in Nansana",
    description: "Accessible residential property on outskirts with development potential.",
    district: "Wakiso",
    county: "Kyadondo East",
    subcounty: "Nansana",
    village: "Nansana",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 180000000,
    latitude: 0.2442,
    longitude: 32.5211,
  },
  {
    plotNumber: "WAK-004-AGR",
    title: "Agricultural Land in Busiro South",
    description: "Fertile agricultural land for farming operations.",
    district: "Wakiso",
    county: "Busiro South",
    subcounty: "Kajjansi",
    village: "Kajjansi",
    size: 3.0,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 150000000,
    latitude: 0.1156,
    longitude: 32.4367,
  },
  {
    plotNumber: "WAK-005-COM",
    title: "Commercial Property near Entebbe Road",
    description: "Commercial land along the busy Entebbe Expressway corridor.",
    district: "Wakiso",
    county: "Kyadondo West",
    subcounty: "Kyadondo West",
    village: "Kyadondo",
    size: 0.4,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 380000000,
    latitude: 0.2178,
    longitude: 32.5056,
  },
  {
    plotNumber: "WAK-006-MIX",
    title: "Mixed-Use Plot near Busiro North",
    description: "Development property suitable for mixed residential-commercial use.",
    district: "Wakiso",
    county: "Busiro North",
    subcounty: "Busiro North",
    village: "Busiro",
    size: 1.0,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.MIXED_USE,
    price: 450000000,
    latitude: 0.1867,
    longitude: 32.4689,
  },
  {
    plotNumber: "WAK-007-REC",
    title: "Recreational Land in Entebbe",
    description: "Ideal for recreational facilities or resort development.",
    district: "Wakiso",
    county: "Entebbe Municipality",
    subcounty: "Entebbe",
    village: "Entebbe",
    size: 2.0,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.LAND,
    price: 280000000,
    latitude: 0.0622,
    longitude: 32.4412,
  },

  // Mukono - Central Region (5 properties)
  {
    plotNumber: "MUK-001-RES",
    title: "Residential Land in Mukono Town",
    description: "Property in the heart of Mukono with commercial potential.",
    district: "Mukono",
    county: "Mukono North",
    subcounty: "Mukono Town",
    village: "Mukono",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 160000000,
    latitude: 0.3547,
    longitude: 33.0022,
  },
  {
    plotNumber: "MUK-002-AGR",
    title: "Agricultural Land in Seeta",
    description: "Farming land with reliable rainfall and fertile soils.",
    district: "Mukono",
    county: "Mukono North",
    subcounty: "Seeta",
    village: "Seeta",
    size: 4.0,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 140000000,
    latitude: 0.4056,
    longitude: 33.0578,
  },
  {
    plotNumber: "MUK-003-RES",
    title: "Residential Home in Namataba",
    description: "Quiet residential area suitable for families.",
    district: "Mukono",
    county: "Mukono South",
    subcounty: "Namataba",
    village: "Namataba",
    size: 0.5,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 140000000,
    latitude: 0.3122,
    longitude: 33.0367,
  },
  {
    plotNumber: "MUK-004-COM",
    title: "Commercial Plot in Mukono",
    description: "Strategic commercial property along Seeta Road.",
    district: "Mukono",
    county: "Mukono North",
    subcounty: "Seeta",
    village: "Seeta",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 220000000,
    latitude: 0.3989,
    longitude: 33.0645,
  },
  {
    plotNumber: "MUK-005-IND",
    title: "Industrial Land near Mukono",
    description: "Industrial property with access to main highways.",
    district: "Mukono",
    county: "Mukono North",
    subcounty: "Mukono Town",
    village: "Mukono",
    size: 0.7,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.INDUSTRIAL,
    price: 200000000,
    latitude: 0.3634,
    longitude: 33.0089,
  },

  // Jinja - Eastern Region (6 properties)
  {
    plotNumber: "JNJ-001-RES",
    title: "Residential Plot in Jinja Central",
    description: "Prime residential land in the industrial hub of Jinja.",
    district: "Jinja",
    county: "Jinja Central",
    subcounty: "Jinja Central",
    village: "Jinja",
    size: 0.5,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.RESIDENTIAL,
    price: 200000000,
    latitude: 0.4267,
    longitude: 33.1333,
  },
  {
    plotNumber: "JNJ-002-COM",
    title: "Commercial Land near Nile Avenue",
    description: "Commercial property with views of the Nile River.",
    district: "Jinja",
    county: "Jinja Central",
    subcounty: "Jinja Central",
    village: "Jinja",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 320000000,
    latitude: 0.4312,
    longitude: 33.1378,
  },
  {
    plotNumber: "JNJ-003-IND",
    title: "Industrial Site in Butembe",
    description: "Industrial property suitable for manufacturing facilities.",
    district: "Jinja",
    county: "Butembe",
    subcounty: "Butembe",
    village: "Butembe",
    size: 1.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.INDUSTRIAL,
    price: 280000000,
    latitude: 0.4189,
    longitude: 33.1456,
  },
  {
    plotNumber: "JNJ-004-RES",
    title: "Residential Home in Kagoma",
    description: "Residential property in emerging Kagoma area.",
    district: "Jinja",
    county: "Kagoma",
    subcounty: "Kagoma",
    village: "Kagoma",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.HOUSE,
    price: 140000000,
    latitude: 0.4578,
    longitude: 33.1189,
  },
  {
    plotNumber: "JNJ-005-AGR",
    title: "Agricultural Land near Jinja",
    description: "Farming land with good water sources.",
    district: "Jinja",
    county: "Jinja Central",
    subcounty: "Jinja Central",
    village: "Jinja",
    size: 2.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 120000000,
    latitude: 0.4422,
    longitude: 33.1289,
  },
  {
    plotNumber: "JNJ-006-MIX",
    title: "Mixed-Use Development in Butembe",
    description: "Large development property near growth corridor.",
    district: "Jinja",
    county: "Butembe",
    subcounty: "Butembe",
    village: "Butembe",
    size: 1.2,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.MIXED_USE,
    price: 380000000,
    latitude: 0.4145,
    longitude: 33.1512,
  },

  // Mbale - Eastern Region (4 properties)
  {
    plotNumber: "MBL-001-RES",
    title: "Residential Land in Bungokho",
    description: "Mountain-view residential property in scenic Mbale region.",
    district: "Mbale",
    county: "Bungokho",
    subcounty: "Bungokho",
    village: "Bungokho",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 120000000,
    latitude: 1.0469,
    longitude: 34.1806,
  },
  {
    plotNumber: "MBL-002-AGR",
    title: "Agricultural Land in Bubulo",
    description: "Fertile agricultural land suitable for cash crops.",
    district: "Mbale",
    county: "Bubulo",
    subcounty: "Bubulo",
    village: "Bubulo",
    size: 3.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 100000000,
    latitude: 1.0889,
    longitude: 34.1922,
  },
  {
    plotNumber: "MBL-003-COM",
    title: "Commercial Property in Mbale Town",
    description: "Commercial land with good accessibility.",
    district: "Mbale",
    county: "Bungokho",
    subcounty: "Bungokho",
    village: "Mbale",
    size: 0.25,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 180000000,
    latitude: 1.0622,
    longitude: 34.1889,
  },
  {
    plotNumber: "MBL-004-RES",
    title: "Residential Home in Bubulo",
    description: "Family home property in peaceful village setting.",
    district: "Mbale",
    county: "Bubulo",
    subcounty: "Bubulo",
    village: "Bubulo",
    size: 0.4,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 100000000,
    latitude: 1.0956,
    longitude: 34.1756,
  },

  // Mbarara - Western Region (6 properties)
  {
    plotNumber: "MBR-001-RES",
    title: "Residential Plot in Mbarara Central",
    description: "Prime residential property in Mbarara town center.",
    district: "Mbarara",
    county: "Mbarara Municipality",
    subcounty: "Mbarara Central",
    village: "Mbarara",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 200000000,
    latitude: -0.6089,
    longitude: 29.7347,
  },
  {
    plotNumber: "MBR-002-COM",
    title: "Commercial Land in Mbarara",
    description: "Commercial property on main Mbarara Street.",
    district: "Mbarara",
    county: "Mbarara Municipality",
    subcounty: "Mbarara Central",
    village: "Mbarara",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 250000000,
    latitude: -0.6134,
    longitude: 29.7389,
  },
  {
    plotNumber: "MBR-003-AGR",
    title: "Agricultural Land in Kashari North",
    description: "Ranch or farming land with pastoral landscape.",
    district: "Mbarara",
    county: "Kashari North",
    subcounty: "Kashari North",
    village: "Kashari",
    size: 5.0,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 180000000,
    latitude: -0.5956,
    longitude: 29.7022,
  },
  {
    plotNumber: "MBR-004-RES",
    title: "Residential Home in Kakoba",
    description: "Suburban residential property with modern facilities.",
    district: "Mbarara",
    county: "Mbarara Municipality",
    subcounty: "Kakoba",
    village: "Kakoba",
    size: 0.45,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 160000000,
    latitude: -0.6289,
    longitude: 29.7156,
  },
  {
    plotNumber: "MBR-005-IND",
    title: "Industrial Plot near Mbarara",
    description: "Industrial property with infrastructure development potential.",
    district: "Mbarara",
    county: "Kashari South",
    subcounty: "Kashari South",
    village: "Kashari",
    size: 1.0,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.INDUSTRIAL,
    price: 220000000,
    latitude: -0.6378,
    longitude: 29.7289,
  },
  {
    plotNumber: "MBR-006-REC",
    title: "Recreational Land in Mbarara",
    description: "Land ideal for resort or leisure development.",
    district: "Mbarara",
    county: "Mbarara Municipality",
    subcounty: "Mbarara Central",
    village: "Mbarara",
    size: 2.5,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.LAND,
    price: 300000000,
    latitude: -0.6056,
    longitude: 29.7478,
  },

  // Gulu - Northern Region (5 properties)
  {
    plotNumber: "GUL-001-RES",
    title: "Residential Land in Gulu Central",
    description: "Post-conflict reconstruction area with development potential.",
    district: "Gulu",
    county: "Gulu Municipality",
    subcounty: "Gulu Central",
    village: "Gulu",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 100000000,
    latitude: 2.7769,
    longitude: 32.2833,
  },
  {
    plotNumber: "GUL-002-COM",
    title: "Commercial Property in Gulu",
    description: "Commercial land on main Gulu Street with good foot traffic.",
    district: "Gulu",
    county: "Gulu Municipality",
    subcounty: "Gulu Central",
    village: "Gulu",
    size: 0.25,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 150000000,
    latitude: 2.7822,
    longitude: 32.2889,
  },
  {
    plotNumber: "GUL-003-AGR",
    title: "Agricultural Land in Aswa",
    description: "Farming land in developing agricultural area.",
    district: "Gulu",
    county: "Aswa",
    subcounty: "Aswa",
    village: "Aswa",
    size: 3.0,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 80000000,
    latitude: 2.8156,
    longitude: 32.3122,
  },
  {
    plotNumber: "GUL-004-RES",
    title: "Residential Home in Gulu",
    description: "Family home in growing residential area.",
    district: "Gulu",
    county: "Gulu Municipality",
    subcounty: "Laroo",
    village: "Laroo",
    size: 0.4,
    tenure: PropertyTenure.TITLED,
    type: PropertyType.HOUSE,
    price: 95000000,
    latitude: 2.7922,
    longitude: 32.2956,
  },
  {
    plotNumber: "GUL-005-IND",
    title: "Industrial Land near Gulu",
    description: "Industrial property suitable for manufacturing.",
    district: "Gulu",
    county: "Gulu Municipality",
    subcounty: "Laroo",
    village: "Laroo",
    size: 0.8,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.INDUSTRIAL,
    price: 140000000,
    latitude: 2.8022,
    longitude: 32.2722,
  },

  // Lira - Northern Region (3 properties)
  {
    plotNumber: "LIR-001-RES",
    title: "Residential Land in Lira Central",
    description: "Residential property in vibrant Lira town.",
    district: "Lira",
    county: "Lira Municipality",
    subcounty: "Lira Municipality",
    village: "Lira",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 110000000,
    latitude: 2.2208,
    longitude: 32.8989,
  },
  {
    plotNumber: "LIR-002-AGR",
    title: "Agricultural Land in Erute North",
    description: "Fertile farming land in Northern agricultural zone.",
    district: "Lira",
    county: "Erute North",
    subcounty: "Erute North",
    village: "Erute",
    size: 4.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 90000000,
    latitude: 2.2678,
    longitude: 32.9456,
  },
  {
    plotNumber: "LIR-003-COM",
    title: "Commercial Property in Lira",
    description: "Commercial land in Lira business district.",
    district: "Lira",
    county: "Lira Municipality",
    subcounty: "Lira Municipality",
    village: "Lira",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 160000000,
    latitude: 2.2267,
    longitude: 32.9045,
  },

  // Masaka - Central Region (3 properties)
  {
    plotNumber: "MSK-001-RES",
    title: "Residential Land in Masaka",
    description: "Residential property in vibrant Masaka region.",
    district: "Masaka",
    county: "Masaka",
    subcounty: "Masaka",
    village: "Masaka",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 140000000,
    latitude: -0.3305,
    longitude: 31.7427,
  },
  {
    plotNumber: "MSK-002-AGR",
    title: "Agricultural Land in Masaka",
    description: "Farming land suitable for bananas and perennial crops.",
    district: "Masaka",
    county: "Masaka",
    subcounty: "Masaka",
    village: "Masaka",
    size: 3.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 110000000,
    latitude: -0.3456,
    longitude: 31.7567,
  },
  {
    plotNumber: "MSK-003-COM",
    title: "Commercial Property in Masaka",
    description: "Commercial land with good market positioning.",
    district: "Masaka",
    county: "Masaka",
    subcounty: "Masaka",
    village: "Masaka",
    size: 0.3,
    tenure: PropertyTenure.LEASEHOLD,
    type: PropertyType.COMMERCIAL,
    price: 200000000,
    latitude: -0.3267,
    longitude: 31.7489,
  },

  // Fort Portal - Western Region (2 properties)
  {
    plotNumber: "FTP-001-RES",
    title: "Residential Land in Fort Portal",
    description: "Mountain-view residential property in tourism hub.",
    district: "Fort Portal",
    county: "Fort Portal",
    subcounty: "Fort Portal",
    village: "Fort Portal",
    size: 0.5,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 150000000,
    latitude: 0.6717,
    longitude: 30.2753,
  },
  {
    plotNumber: "FTP-002-AGR",
    title: "Agricultural Land near Fort Portal",
    description: "Farming land in scenic Western region.",
    district: "Fort Portal",
    county: "Fort Portal",
    subcounty: "Fort Portal",
    village: "Fort Portal",
    size: 4.0,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 120000000,
    latitude: 0.6822,
    longitude: 30.2867,
  },

  // Kabale - Western Region (2 properties)
  {
    plotNumber: "KBL-001-RES",
    title: "Residential Land in Kabale",
    description: "Mountain property with panoramic views.",
    district: "Kabale",
    county: "Kabale",
    subcounty: "Kabale",
    village: "Kabale",
    size: 0.4,
    tenure: PropertyTenure.FREEHOLD,
    type: PropertyType.RESIDENTIAL,
    price: 130000000,
    latitude: -1.2577,
    longitude: 29.9244,
  },
  {
    plotNumber: "KBL-002-AGR",
    title: "Agricultural Land in Kabale",
    description: "Terraced farming land suitable for vegetables and grains.",
    district: "Kabale",
    county: "Kabale",
    subcounty: "Kabale",
    village: "Kabale",
    size: 2.5,
    tenure: PropertyTenure.MAILO,
    type: PropertyType.AGRICULTURAL,
    price: 95000000,
    latitude: -1.2656,
    longitude: 29.9367,
  },
];

async function main() {
  console.log("🌱 Seeding 50 properties across Uganda...\n");

  let created = 0;
  let updated = 0;

  for (const prop of PROPERTIES) {
    const result = await prisma.property.upsert({
      where: { plotNumber: prop.plotNumber },
      update: {
        title: prop.title,
        description: prop.description,
        size: prop.size,
        price: prop.price,
        latitude: prop.latitude,
        longitude: prop.longitude,
      },
      create: {
        plotNumber: prop.plotNumber,
        title: prop.title,
        description: prop.description,
        district: prop.district,
        county: prop.county,
        subcounty: prop.subcounty,
        village: prop.village,
        size: prop.size,
        tenure: prop.tenure,
        type: prop.type,
        price: prop.price,
        status: PropertyStatus.ACTIVE,
        latitude: prop.latitude,
        longitude: prop.longitude,
        isFeatured: Math.random() > 0.7,
        isPublicListing: true,
      },
    });

    created++;
  }

  console.log(`✅ ${created} properties seeded`);
  console.log("\n📊 Distribution Summary:");
  console.log("   Central Region: 20 properties");
  console.log("   Eastern Region: 13 properties");
  console.log("   Western Region: 12 properties");
  console.log("   Northern Region: 5 properties");
  console.log("\n🎉 Property seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
